In [3]:
import pandas as pd

In [316]:
mvps = pd.read_csv("mvps.csv")

In [317]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Julius Erving,30,PHI,28.0,454.0,690,0.658,82,...,8.0,4.4,2.1,1.8,0.521,0.222,0.787,13.8,0.231,1981
1,1,2,Larry Bird,24,BOS,20.0,423.0,690,0.613,82,...,10.9,5.5,2.0,0.8,0.478,0.270,0.863,10.8,0.160,1981
2,2,3,Kareem Abdul-Jabbar,33,LAL,8.0,286.0,690,0.414,80,...,10.3,3.4,0.7,2.9,0.574,0.000,0.766,14.3,0.230,1981
3,3,4,Moses Malone,25,HOU,8.0,180.0,690,0.261,80,...,14.8,1.8,1.0,1.9,0.522,0.333,0.757,13.7,0.202,1981
4,4,5,George Gervin,28,SAS,1.0,83.0,690,0.120,82,...,5.1,3.2,1.1,0.7,0.492,0.257,0.826,10.5,0.182,1981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,4,5,Jalen Brunson,27,NYK,0.0,142.0,990,0.143,77,...,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198,2024
706,5,6,Jayson Tatum,25,BOS,0.0,86.0,990,0.087,74,...,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189,2024
707,6,7,Anthony Edwards,22,MIN,0.0,18.0,990,0.018,79,...,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130,2024
708,7,8,Domantas Sabonis,27,SAC,0.0,3.0,990,0.003,82,...,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206,2024
709,8,9,Kevin Durant,35,PHO,0.0,1.0,990,0.001,75,...,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142,2024

In [318]:
mvps = mvps[["Player", "Pts Won", "Pts Max", "Share", "Year"]]

In [319]:
mvps

                  Player  Pts Won  Pts Max  Share  Year
0          Julius Erving    454.0      690  0.658  1981
1             Larry Bird    423.0      690  0.613  1981
2    Kareem Abdul-Jabbar    286.0      690  0.414  1981
3           Moses Malone    180.0      690  0.261  1981
4          George Gervin     83.0      690  0.120  1981
..                   ...      ...      ...    ...   ...
705        Jalen Brunson    142.0      990  0.143  2024
706         Jayson Tatum     86.0      990  0.087  2024
707      Anthony Edwards     18.0      990  0.018  2024
708     Domantas Sabonis      3.0      990  0.003  2024
709         Kevin Durant      1.0      990  0.001  2024

[710 rows x 5 columns]

In [289]:
players = pd.read_csv("players.csv")

In [290]:
players

,Unnamed: 0,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,0,1,Adrian Dantley,25,UTA,SF,80,NaN,42.7,11.4,...,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1981
1,1,2,Moses Malone,25,HOU,C,80,NaN,40.6,10.1,...,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1981
2,2,3,George Gervin,28,SAS,SG,82,82,33.7,10.4,...,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1981
3,3,4,Kareem Abdul-Jabbar,33,LAL,C,80,NaN,37.2,10.5,...,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1981
4,4,5,David Thompson,26,DEN,SG,77,NaN,34.0,9.5,...,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,NaN,1981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24274,754,569,Ron Harper Jr.,23,TOR,PF,1,0,4.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,NaN,2024
24275,755,570,Justin Jackson,28,MIN,SF,2,0,0.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
24276,756,571,Dmytro Skapintsev,25,NYK,C,2,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
24277,757,572,Javonte Smart,24,PHI,PG,1,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
24278,758,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024

In [291]:
del players["Unnamed: 0"]

In [292]:
del players["Rk"]

In [293]:
del players["Awards"]

In [294]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Adrian Dantley,25,UTA,SF,80,NaN,42.7,11.4,20.3,.559,...,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,1981
1,Moses Malone,25,HOU,C,80,NaN,40.6,10.1,19.3,.522,...,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,1981
2,George Gervin,28,SAS,SG,82,82,33.7,10.4,21.1,.492,...,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,1981
3,Kareem Abdul-Jabbar,33,LAL,C,80,NaN,37.2,10.5,18.2,.574,...,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,1981
4,David Thompson,26,DEN,SG,77,NaN,34.0,9.5,18.8,.506,...,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,1981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24274,Ron Harper Jr.,23,TOR,PF,1,0,4.0,0.0,0.0,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,2024
24275,Justin Jackson,28,MIN,SF,2,0,0.5,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024
24276,Dmytro Skapintsev,25,NYK,C,2,0,1.0,0.0,0.5,.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024
24277,Javonte Smart,24,PHI,PG,1,0,1.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024
24278,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.474,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024

In [295]:
players = players[~players["Player"].str.contains("Player")]

In [296]:
players = players[~players["Player"].str.contains("League Average")]

In [297]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Adrian Dantley,25,UTA,SF,80,NaN,42.7,11.4,20.3,.559,...,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,1981
1,Moses Malone,25,HOU,C,80,NaN,40.6,10.1,19.3,.522,...,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,1981
2,George Gervin,28,SAS,SG,82,82,33.7,10.4,21.1,.492,...,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,1981
3,Kareem Abdul-Jabbar,33,LAL,C,80,NaN,37.2,10.5,18.2,.574,...,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,1981
4,David Thompson,26,DEN,SG,77,NaN,34.0,9.5,18.8,.506,...,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,1981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24273,Danny Green,36,PHI,SG,2,0,9.0,0.0,1.0,.000,...,0.0,1.0,1.0,0.5,0.5,0.0,0.0,0.5,0.0,2024
24274,Ron Harper Jr.,23,TOR,PF,1,0,4.0,0.0,0.0,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,2024
24275,Justin Jackson,28,MIN,SF,2,0,0.5,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024
24276,Dmytro Skapintsev,25,NYK,C,2,0,1.0,0.0,0.5,.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024
24277,Javonte Smart,24,PHI,PG,1,0,1.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2024

In [298]:
players["Player"] = players["Player"].str.replace("*", "", regex=False)

In [299]:
players.head(50)

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Adrian Dantley,25,UTA,SF,80,NaN,42.7,11.4,20.3,.559,...,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,1981
1,Moses Malone,25,HOU,C,80,NaN,40.6,10.1,19.3,.522,...,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,1981
2,George Gervin,28,SAS,SG,82,82,33.7,10.4,21.1,.492,...,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,1981
3,Kareem Abdul-Jabbar,33,LAL,C,80,NaN,37.2,10.5,18.2,.574,...,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,1981
4,David Thompson,26,DEN,SG,77,NaN,34.0,9.5,18.8,.506,...,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,1981
5,Otis Birdsong,25,KCK,SG,71,NaN,36.5,10.0,18.4,.544,...,1.7,2.0,3.6,3.3,1.3,0.3,2.4,2.4,24.6,1981
6,Julius Erving,30,PHI,SF,82,82,35.0,9.7,18.6,.521,...,3.0,5.0,8.0,4.4,2.1,1.8,3.2,2.8,24.6,1981
7,Mike Mitchell,25,CLE,SF,82,82,39.0,10.4,21.8,.476,...,2.6,3.5,6.1,1.7,0.8,0.6,2.1,2.4,24.5,1981
8,World B. Free,27,GSW,SG,65,NaN,36.5,7.9,17.8,.446,...,0.7,1.7,2.4,5.6,1.3,0.2,3.0,2.8,24.1,1981
9,Alex English,27,DEN,SF,81,NaN,38.2,9.5,19.2,.494,...,3.4,4.6,8.0,3.6,1.3,1.2,3.0,3.1,23.8,1981
10,Jamaal Wilkes,27,LAL,SF,81,NaN,37.4,9.7,18.5,.526,...,1.8,3.6,5.4,2.9,1.5,0.4,2.6,2.8,22.6,1981
11,Dan Issel,32,DEN,C,80,NaN,33.0,7.7,15.3,.503,...,2.9,5.6,8.5,2.0,1.0,0.7,1.6,3.1,21.9,1981
12,Bernard King,24,GSW,SF,81,NaN,36.0,9.0,15.4,.588,...,2.2,4.6,6.8,3.5,0.9,0.4,3.3,3.8,21.9,1981
13,John Drew,26,ATL,SF,67,NaN,31.0,7.5,16.4,.456,...,2.2,3.6,5.7,1.2,1.5,0.2,2.9,3.9,21.7,1981
14,Magic Johnson,21,LAL,SG,37,NaN,37.1,8.4,15.9,.532,...,2.7,5.9,8.6,8.6,3.4,0.7,3.9,2.7,21.6,1981
15,Mike Newlin,32,NJN,SG,79,NaN,36.8,8.0,16.1,.497,...,1.0,1.8,2.8,3.8,1.1,0.1,3.1,3.0,21.4,1981
16,Larry Bird,24,BOS,PF,82,82,39.5,8.8,18.3,.478,...,2.3,8.6,10.9,5.5,2.0,0.8,3.5,2.9,21.2,1981
17,Darrell Griffith,22,UTA,SG,81,NaN,35.4,8.8,19.1,.464,...,1.0,2.6,3.6,2.4,1.3,0.5,2.9,2.7,20.6,1981
18,Marques Johnson,24,MIL,SF,76,NaN,33.4,8.4,15.2,.552,...,3.0,3.9,6.8,4.6,1.5,0.5,2.5,2.6,20.3,1981
19,Bill Cartwright,23,NYK,C,82,81,35.7,7.5,13.6,.554,...,2.0,5.5,7.5,1.4,0.6,1.0,2.4,3.2,20.1,1981
20,Ray Williams,26,NYK,PG,79,79,34.7,7.8,16.9,.461,...,1.5,2.5,4.1,5.5,2.3,0.5,3.0,3.4,19.7,1981
21,Cliff Robinson,20,NJN,PF,63,NaN,28.9,8.3,17.0,.491,...,1.9,5.7,7.6,1.7,0.9,0.8,2.9,3.4,19.5,1981
22,Freeman Williams,24,SDC,SG,82,NaN,24.1,7.8,16.8,.465,...,0.9,0.7,1.6,2.0,1.1,0.1,2.0,1.9,19.3,1981
23,Eddie Johnson,25,ATL,SG,75,NaN,35.9,7.6,15.1,.504,...,0.8,1.6,2.4,5.4,1.7,0.1,2.6,2.5,19.1,1981
24,Scott Wedman,28,KCK,SF,81,NaN,35.8,8.5,17.7,.477,...,1.6,3.8,5.3,2.8,1.2,0.6,2.0,3.6,19.0,1981
25,Joe Barry Carroll,22,GSW,C,82,NaN,35.6,7.5,15.3,.491,...,3.3,5.9,9.3,1.4,0.6,1.5,3.0,3.8,18.9,1981
26,Robert Parish,27,BOS,C,82,82,28.0,7.7,14.2,.545,...,3.0,6.5,9.5,1.8,1.0,2.6,2.3,3.8,18.9,1981
27,Reggie Theus,23,CHI,SG,82,82,34.4,6.6,13.4,.495,...,1.5,2.0,3.5,5.2,1.5,0.2,3.2,3.1,18.9,1981
28,Dennis Johnson,26,PHO,PG,79,NaN,33.1,6.7,15.4,.436,...,2.0,2.6,4.6,3.7,1.7,0.8,2.6,3.1,18.8,1981
29,Truck Robinson,29,PHO,PF,82,82,37.7,7.9,15.6,.505,...,2.6,7.0,9.6,2.5,0.8,0.5,3.0,2.7,18.8,1981
30,Jack Sikma,25,SEA,C,82,82,35.6,7.3,16.0,.454,...,2.2,8.1,10.4,3.0,1.0,1.1,2.5,3.4,18.7,1981
31,Walter Davis,26,PHO,SG,78,NaN,28.0,7.6,14.1,.539,...,0.8,1.8,2.6,3.9,1.2,0.2,2.8,2.5,18.0,1981
32,Artis Gilmore,31,CHI,C,82,82,34.5,6.7,10.0,.670,...,2.7,7.4,10.1,2.1,0.6,2.4,2.9,3.6,17.9,1981
33,Elvin Hayes,35,WSB,PF,81,NaN,36.2,7.2,16.0,.451,...,2.9,6.8,9.7,1.2,0.8,2.1,2.3,3.7,17.8,1981
34,John Long,24,DET,SG,59,NaN,29.7,7.5,16.2,.461,...,1.6,1.7,3.3,1.8,1.6,0.4,2.6,2.8,17.7,1981
35,James Silas,31,SAS,PG,75,NaN,27.4,6.3,13.3,.477,...,0.6,2.5,3.1,3.8,0.7,0.2,2.1,1.7,17.7,1981
36,Dan Roundfield,27,ATL,PF,63,NaN,33.8,6.8,12.8,.527,...,3.7,6.4,10.1,2.6,1.2,1.9,2.8,4.1,17.6,1981
37,Phil Ford,24,KCK,PG,66,NaN,34.7,6.4,13.4,.478,...,0.4,1.5,1.9,8.8,1.5,0.1,3.7,2.9,17.5,1981
38,Billy Knight,28,IND,SG,82,NaN,29.1,6.7,12.5,.533,...,2.3,2.7,5.0,1.9,1.0,0.1,2.2,1.9,17.5,1981
39,Kevin Grevey,27,WSB,SG,75,NaN,34.9,6.7,14.7,.453,...,0.9,2.0,2.9,4.0,0.9,0.2,1.9,2.1,17.2,1981
40,Norm Nixon,25,LAL,PG,79,NaN,37.5,7.3,15.3,.476,...,0.8,2.1,2.9,8.8,1.8,0.1,3.6,2.9,17.1,1981
41,Jim Paxson,23,POR,SG,79,NaN,34.2,7.4,13.8,.536,...,0.9,1.7,2.7,3.8,1.8,0.1,1.7,2.2,17.1,1981
42,Mychal Thompson,26,POR,C,79,NaN,35.3,7.2,14.6,.494,...,2.8,5.9,8.7,3.6,0.8,2.2,3.1,3.3,17.0,1981
43,Junior Bridgeman,27,MIL,SF,77,NaN,28.8,7.0,14.3,.487,...,1.0,2.7,3.8,3.0,1.1,0.4,1.9,2.4,16.8,1981
44,Phil Smith,28,SDC,SG,76,NaN,31.3,6.8,13.9,.491,...,0.6,1.4,2.1,4.9,1.1,0.2,2.3,3.0,16.8,1981
45,Calvin Murphy,32,HOU,PG,76,NaN,26.5,6.9,14.1,.492,...,0.4,0.7,1.1,2.9,1.5,0.1,1.7,2.8,16.7,1981
46,Paul Westphal,30,SEA,SG,36,NaN,29.9,6.1,13.9,.442,...,0.3,1.6,1.9,4.1,1.3,0.4,2.2,1.9,16.7,1981
47,Michael Ray Richardson,25,NYK,SG,79,79,40.2,6.6,14.1,.469,...,2.2,4.7,6.9,7.9,2.9,0.4,3.8,3.3,16.4,1981
48,Campy Russell,29,NYK,SF,79,79,36.3,6.4,13.9,.464,...,1.4,3.1,4.5,3.3,1.3,0.1,2.7,3.1,16.4,1981
49,Purvis Short,23,GSW,SF,79,NaN,29.2,6.9,14.6,.475,...,1.9,3.0,4.9,3.2,1.0,0.2,1.8,3.1,16.1,1981

In [300]:
players.groupby(["Player", "Year"]).get_group(("Greg Anderson", 1991))

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
4349,Greg Anderson,26,3TM,PF,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
4350,Greg Anderson,26,MIL,PF,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
4351,Greg Anderson,26,NJN,PF,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
4352,Greg Anderson,26,DEN,PF,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991

In [301]:
def single_row(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Team"] == "TOT"]
        row["Team"] = df.iloc[-1,:]["Team"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_row)

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\1763002476.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  players = players.groupby(["Player", "Year"]).apply(single_row)

In [302]:
players.head(20)

                                 Player Age Team Pos   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1986 2110      A.C. Green  22  LAL  PF  82   1  18.8  2.5   4.7
              1987 2405      A.C. Green  23  LAL  PF  79  72  28.4  4.0   7.4
              1988 2797      A.C. Green  24  LAL  PF  82  64  32.1  3.9   7.8
              1989 3215      A.C. Green  25  LAL  PF  82  82  30.6  4.9   9.2
              1990 3670      A.C. Green  26  LAL  PF  82  82  33.0  4.7   9.8
              1991 4218      A.C. Green  27  LAL  PF  82  21  26.4  3.1   6.6
              1992 4586      A.C. Green  28  LAL  PF  82  53  35.4  4.7   9.8
              1993 5071      A.C. Green  29  LAL  PF  82  55  34.4  4.6   8.6
              1994 5501      A.C. Green  30  PHO  PF  82  55  34.5  5.7  11.3
              1995 6057      A.C. Green  31  PHO  SF  82  52  32.8  3.8   7.5
              1996 6637      A.C. Green  32  PHO  SF  82  36  25.8  2.6   5.4
              1998 7795      A.C. Green  34  DAL  PF  82  68  32.3  3.0   6.5
              1999 8413      A.C. Green  35  DAL  PF  50  35  18.5  2.2   5.1
              2000 8943      A.C. Green  36  LAL  PF  82  82  23.5  2.1   4.7
              2001 9502      A.C. Green  37  MIA  PF  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 9120   A.J. Bramlett  23  CLE   C   8   0   7.6  0.5   2.6
A.J. English  1991 4223    A.J. English  23  WSB  SG  70  12  20.6  3.6   8.2
              1992 4629    A.J. English  24  WSB  SG  81   6  20.6  4.5  10.4
A.J. Green    2023 23330     A.J. Green  23  MIL  SG  35   1   9.9  1.5   3.6
              2024 24006     A.J. Green  24  MIL  SG  56   0  11.0  1.5   3.5

                           FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player        Year              ...
A.C. Green    1986 2110   .539  ...  2.0  2.7  4.6  0.7  0.6  0.6  1.2  2.8
              1987 2405   .538  ...  2.7  5.1  7.8  1.1  0.9  1.0  1.3  2.2
              1988 2797   .503  ...  3.0  5.7  8.7  1.1  1.1  0.5  1.5  2.5
              1989 3215   .529  ...  3.1  5.9  9.0  1.3  1.1  0.7  1.5  2.1
              1990 3670   .478  ...  3.2  5.5  8.7  1.1  0.8  0.6  1.4  2.5
              1991 4218   .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 4586   .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 5071   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 5501   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 6057   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 6637   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1998 7795   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 8413   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 8943   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 9502   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 9120   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 4223   .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 4629   .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Green    2023 23330  .424  ...  0.2  1.1  1.3  0.6  0.2  0.0  0.3  0.9
              2024 24006  .423  ...  0.2  1.0  1.1  0.5  0.2  0.1  0.2  0.9

                           PTS  Year
Player        Year
A.C. Green    1986 2110    6.4  1986
              1987 2405   10.8  1987
              1988 2797   11.4  1988
              1989 3215   13.3  1989
              1990 3670   12.9  1990
              1991 4218    9.1  1991
              1992 4586   13.6  1992
              1993 5071   12.8  1993
              1994 5501   14.7  1994
              1995 6057   11.2  1995
              1996 6637    7.5  1996
              1998 7795    7.3  1998
              1999 8413    4.9  1999
              2000 8943    5.0  2000
              2001 9502    4.5  2001
A.J. Bramlett 2000 9120    1.0  2000
A.J. English  1991 4223    8.8  1991
              1992 4629   10.9  1992
A.J. Green    2023 23330   4.4  2023
              2024 24006   4.5  2024

[20 rows x 30 columns]

In [303]:
players.index = players.index.droplevel()

In [304]:
players.index = players.index.droplevel()

In [305]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
2110,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
2405,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
2797,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3215,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
3670,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12332,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.6,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,2006
9939,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
10441,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
11647,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
12260,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [311]:
players.to_csv("tempplay.csv")

In [307]:
players.head()

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
2110,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
2405,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
2797,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3215,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
3670,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990

In [327]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [328]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,0.7,0.6,0.6,1.2,2.8,6.4,1986,NaN,NaN,NaN
1,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,1.1,0.9,1.0,1.3,2.2,10.8,1987,NaN,NaN,NaN
2,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,1.1,1.1,0.5,1.5,2.5,11.4,1988,NaN,NaN,NaN
3,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,1.3,1.1,0.7,1.5,2.1,13.3,1989,NaN,NaN,NaN
4,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,1.1,0.8,0.6,1.4,2.5,12.9,1990,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16945,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,NaN,NaN,NaN
16946,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,NaN,NaN,NaN
16947,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
16948,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
16949,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN

In [312]:
combined.to_csv("tempcombined.csv")

In [329]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [330]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,0.7,0.6,0.6,1.2,2.8,6.4,1986,0.0,0.0,0.0
1,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,1.1,0.9,1.0,1.3,2.2,10.8,1987,0.0,0.0,0.0
2,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,1.1,1.1,0.5,1.5,2.5,11.4,1988,0.0,0.0,0.0
3,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,1.3,1.1,0.7,1.5,2.1,13.3,1989,0.0,0.0,0.0
4,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,1.1,0.8,0.6,1.4,2.5,12.9,1990,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16945,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,0.0,0.0,0.0
16946,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,0.0,0.0,0.0
16947,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,0.0,0.0,0.0
16948,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
16949,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0

In [249]:
teams = pd.read_csv("teams.csv")

In [250]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics*
1,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers*
2,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks*
3,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
4,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1399,13,50,32,.610,—,117.9,115.6,2.30,2024,Dallas Mavericks*
1400,14,49,33,.598,1.0,115.1,110.7,4.46,2024,New Orleans Pelicans*
1401,15,41,41,.500,9.0,114.3,113.2,1.24,2024,Houston Rockets
1402,16,27,55,.329,23.0,105.8,112.8,-6.57,2024,Memphis Grizzlies
1403,17,22,60,.268,28.0,112.1,118.6,-5.80,2024,San Antonio Spurs

In [41]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics*
1,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers*
2,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks*
3,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
4,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets
5,5,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1981,Central Division
6,6,60,22,.732,—,113.1,105.9,7.14,1981,Milwaukee Bucks*
7,7,45,37,.549,15.0,109.0,107.0,2.34,1981,Chicago Bulls*
8,8,44,38,.537,16.0,107.6,106.2,1.72,1981,Indiana Pacers*
9,9,31,51,.378,29.0,104.9,108.0,-2.37,1981,Atlanta Hawks
10,10,28,54,.341,32.0,105.7,110.6,-4.15,1981,Cleveland Cavaliers
11,11,21,61,.256,39.0,99.7,106.0,-5.58,1981,Detroit Pistons
12,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1981,Midwest Division
13,1,52,30,.634,—,112.3,109.4,2.18,1981,San Antonio Spurs*
14,2,40,42,.488,12.0,106.9,106.9,-0.49,1981,Kansas City Kings*
15,3,40,42,.488,12.0,108.3,107.9,-0.20,1981,Houston Rockets*
16,4,37,45,.451,15.0,121.8,122.3,-0.95,1981,Denver Nuggets
17,5,28,54,.341,24.0,101.2,107.1,-5.99,1981,Utah Jazz
18,6,15,67,.183,37.0,101.5,109.9,-8.33,1981,Dallas Mavericks
19,7,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1981,Pacific Division
20,8,57,25,.695,—,110.0,104.5,4.83,1981,Phoenix Suns*
21,9,54,28,.659,3.0,111.2,107.3,3.27,1981,Los Angeles Lakers*
22,10,45,37,.549,12.0,110.7,109.8,0.52,1981,Portland Trail Blazers*
23,11,39,43,.476,18.0,109.8,111.0,-1.41,1981,Golden State Warriors
24,12,36,46,.439,21.0,106.5,108.1,-1.78,1981,San Diego Clippers
25,13,34,48,.415,23.0,104.0,105.7,-1.84,1981,Seattle SuperSonics
26,0,63,19,.768,—,112.0,105.6,6.35,1982,Boston Celtics*
27,1,58,24,.707,5.0,111.2,105.5,5.74,1982,Philadelphia 76ers*
28,2,44,38,.537,19.0,106.7,106.0,0.87,1982,New Jersey Nets*
29,3,43,39,.524,20.0,103.5,102.6,1.06,1982,Washington Bullets*

In [251]:
teams = teams[~teams["W"].str.contains("Division")]

In [252]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\390097362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [253]:
teams.head(5)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics
1,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers
2,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks
3,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
4,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets

In [254]:
df = pd.read_csv('nicknames.txt', delimiter=',')  
df.to_csv('nicknames.csv', index=False)

In [255]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()

In [256]:
lines

['Abbreviation,Name\n',
 'ATL,Atlanta Hawks\n',
 'BRK,Brooklyn Nets\n',
 'BKN,Brooklyn Nets\n',
 'BOS,Boston Celtics\n',
 'CHA,Charlotte Bobcats\n',
 'CHH,Charlotte Hornets\n',
 'CHO,Charlotte Hornets\n',
 'CHI,Chicago Bulls\n',
 'CLE,Cleveland Cavaliers\n',
 'DAL,Dallas Mavericks\n',
 'DEN,Denver Nuggets\n',
 'DET,Detroit Pistons\n',
 'GSW,Golden State Warriors\n',
 'HOU,Houston Rockets\n',
 'IND,Indiana Pacers\n',
 'LAC,Los Angeles Clippers\n',
 'LAL,Los Angeles Lakers\n',
 'MEM,Memphis Grizzlies\n',
 'MIA,Miami Heat\n',
 'MIL,Milwaukee Bucks\n',
 'MIN,Minnesota Timberwolves\n',
 'NJN,New Jersey Nets\n',
 'NOH,New Orleans Hornets\n',
 'NOP,New Orleans Pelicans\n',
 'NOK,New Orleans/Oklahoma City Hornets\n',
 'NYK,New York Knicks\n',
 'OKC,Oklahoma City Thunder\n',
 'ORL,Orlando Magic\n',
 'PHI,Philadelphia 76ers\n',
 'PHX,Phoenix Suns\n',
 'PHO,Phoenix Suns\n',
 'POR,Portland Trail Blazers\n',
 'SEA,Seattle SuperSonics\n',
 'SAC,Sacramento Kings\n',
 'SAS,San Antonio Spurs\n',
 'TOR,Toronto Raptors\n',
 'UTA,Utah Jazz\n',
 'VAN,Vancouver Grizzlies\n',
 'WAS,Washington Wizards\n',
 'WSB,Washington Bullets\n']

In [257]:
for line in lines[1:]:
    abbrev,name = line.replace("\n", "").split(",")
    nicknames[abbrev] = name

In [258]:
nicknames

{'ATL': 'Atlanta Hawks',
 'BRK': 'Brooklyn Nets',
 'BKN': 'Brooklyn Nets',
 'BOS': 'Boston Celtics',
 'CHA': 'Charlotte Bobcats',
 'CHH': 'Charlotte Hornets',
 'CHO': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls',
 'CLE': 'Cleveland Cavaliers',
 'DAL': 'Dallas Mavericks',
 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers',
 'LAL': 'Los Angeles Lakers',
 'MEM': 'Memphis Grizzlies',
 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks',
 'MIN': 'Minnesota Timberwolves',
 'NJN': 'New Jersey Nets',
 'NOH': 'New Orleans Hornets',
 'NOP': 'New Orleans Pelicans',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'NYK': 'New York Knicks',
 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic',
 'PHI': 'Philadelphia 76ers',
 'PHX': 'Phoenix Suns',
 'PHO': 'Phoenix Suns',
 'POR': 'Portland Trail Blazers',
 'SEA': 'Seattle SuperSonics',
 'SAC': 'Sacramento Kings',
 'SAS': 'San Antonio Spurs',
 'TOR': 'Toronto Raptors',
 'UTA': 'Utah Jazz',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'WSB': 'Washington Bullets'}

In [331]:
combined["Tm"] = combined["Team"].map(nicknames)

In [332]:
combined.head(5)

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Tm
0,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,0.6,0.6,1.2,2.8,6.4,1986,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,0.9,1.0,1.3,2.2,10.8,1987,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,1.1,0.5,1.5,2.5,11.4,1988,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,1.1,0.7,1.5,2.1,13.3,1989,0.0,0.0,0.0,Los Angeles Lakers
4,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,0.8,0.6,1.4,2.5,12.9,1990,0.0,0.0,0.0,Los Angeles Lakers

In [333]:
teams.rename(columns={'Team': 'Tm'}, inplace=True)

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\2590539626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams.rename(columns={'Team': 'Tm'}, inplace=True)

In [262]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Tm
0,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics
1,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers
2,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks
3,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
4,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1399,13,50,32,.610,—,117.9,115.6,2.30,2024,Dallas Mavericks
1400,14,49,33,.598,1.0,115.1,110.7,4.46,2024,New Orleans Pelicans
1401,15,41,41,.500,9.0,114.3,113.2,1.24,2024,Houston Rockets
1402,16,27,55,.329,23.0,105.8,112.8,-6.57,2024,Memphis Grizzlies
1403,17,22,60,.268,28.0,112.1,118.6,-5.80,2024,San Antonio Spurs

In [334]:
stats = combined.merge(teams, how="outer", on=["Tm", "Year"])

In [335]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Share,Tm,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Art Collins,26,ATL,SG,29,NaN,13.6,1.2,3.4,.354,...,0.000,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
1,Charlie Criss,32,ATL,PG,66,NaN,25.9,3.3,7.3,.454,...,0.000,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
2,Craig Shelton,23,ATL,SF,55,NaN,10.7,1.8,4.0,.457,...,0.000,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
3,Dan Roundfield,27,ATL,PF,63,NaN,33.8,6.8,12.8,.527,...,0.000,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
4,Eddie Johnson,25,ATL,SG,75,NaN,35.9,7.6,15.1,.504,...,0.000,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16954,Chauncey Billups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16955,Stephen Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16956,Goran DragiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16957,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16958,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
stats = stats[:-1]

In [140]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Share,Tm,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Art Collins,26,ATL,SG,29,NaN,13.6,1.2,3.4,.354,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
1,Charlie Criss,32,ATL,PG,66,NaN,25.9,3.3,7.3,.454,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
2,Craig Shelton,23,ATL,SF,55,NaN,10.7,1.8,4.0,.457,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
3,Dan Roundfield,27,ATL,PF,63,NaN,33.8,6.8,12.8,.527,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
4,Eddie Johnson,25,ATL,SG,75,NaN,35.9,7.6,15.1,.504,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17007,Kyle Kuzma,28,WAS,PF,70,70,32.6,8.7,18.8,.463,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17008,Landry Shamet,26,WAS,SG,46,5,15.8,2.6,6.0,.431,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17009,Patrick Baldwin Jr.,21,WAS,SF,38,7,13.0,1.6,4.1,.381,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17010,Tristan Vukcevic,20,WAS,C,10,4,15.3,2.9,6.7,.433,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17011,Tyus Jones,27,WAS,PG,66,66,29.3,4.9,10.1,.489,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29

In [141]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
2110,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
2405,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
2797,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3215,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
3670,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12332,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.6,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,2006
9939,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
10441,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
11647,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
12260,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [336]:
players = players[~players["Player"].str.contains("Player")]

In [337]:
players = players[~players["Player"].str.contains("League Average")]

In [338]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
2110,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
2405,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
2797,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3215,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
3670,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12332,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.6,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,2006
9939,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
10441,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
11647,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
12260,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [248]:
stats.to_csv("temp4.csv")

In [232]:
stats = stats[:-1]

In [233]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Share,Tm,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Art Collins,26,ATL,SG,29,NaN,13.6,1.2,3.4,.354,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
1,Charlie Criss,32,ATL,PG,66,NaN,25.9,3.3,7.3,.454,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
2,Craig Shelton,23,ATL,SF,55,NaN,10.7,1.8,4.0,.457,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
3,Dan Roundfield,27,ATL,PF,63,NaN,33.8,6.8,12.8,.527,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
4,Eddie Johnson,25,ATL,SG,75,NaN,35.9,7.6,15.1,.504,...,0.0,Atlanta Hawks,9.0,31,51,.378,29.0,104.9,108.0,-2.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17007,Kyle Kuzma,28,WAS,PF,70,70,32.6,8.7,18.8,.463,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17008,Landry Shamet,26,WAS,SG,46,5,15.8,2.6,6.0,.431,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17009,Patrick Baldwin Jr.,21,WAS,SF,38,7,13.0,1.6,4.1,.381,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17010,Tristan Vukcevic,20,WAS,C,10,4,15.3,2.9,6.7,.433,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29
17011,Tyus Jones,27,WAS,PG,66,66,29.3,4.9,10.1,.489,...,0.0,Washington Wizards,16.0,15,67,.183,32.0,113.7,123.0,-9.29

In [234]:
del stats["Unnamed: 0"]

In [236]:
stats = stats.apply(pd.to_numeric, errors="ignore")

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\3865212684.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  stats = stats.apply(pd.to_numeric, errors="ignore")

In [237]:
stats.dtypes

Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Tm          object
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

In [238]:
stats["W"].unique()

array(['31', '42', '43', '40', '34', '50', '57', '52', '41', '38', '46',
       '56', '28', '25', '33', '35', '13', '26', '30', '37', '47', '53',
       '44', '60', '48', '24', '29', '20', '36', '62', '63', '67', '59',
       '51', '32', '15', '19', '49', '45', '66', '39', '55', '64', '21',
       'Central Division', '18', '7', '54', '23', '27', '61', '72', '69',
       '17', '22', '11', '58', '14', '73', '65', '12', '9',
       'Midwest Division', '16', 'Northwest Division', 'Pacific Division',
       '10', 'Southeast Division', 'Southwest Division', '8'],
      dtype=object)

In [313]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,22,LAL,PF,82,1,18.8,2.5,4.7,.539,...,0.7,0.6,0.6,1.2,2.8,6.4,1986,NaN,NaN,NaN
1,A.C. Green,23,LAL,PF,79,72,28.4,4.0,7.4,.538,...,1.1,0.9,1.0,1.3,2.2,10.8,1987,NaN,NaN,NaN
2,A.C. Green,24,LAL,PF,82,64,32.1,3.9,7.8,.503,...,1.1,1.1,0.5,1.5,2.5,11.4,1988,NaN,NaN,NaN
3,A.C. Green,25,LAL,PF,82,82,30.6,4.9,9.2,.529,...,1.3,1.1,0.7,1.5,2.1,13.3,1989,NaN,NaN,NaN
4,A.C. Green,26,LAL,PF,82,82,33.0,4.7,9.8,.478,...,1.1,0.8,0.6,1.4,2.5,12.9,1990,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16959,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.3,0.2,0.1,0.6,1.4,3.3,2006,NaN,NaN,NaN
16960,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.5,0.4,1.0,1.1,2.6,6.9,2002,NaN,NaN,NaN
16961,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.3,0.2,0.6,1.0,2.6,6.6,2003,NaN,NaN,NaN
16962,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
16963,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN

In [314]:
names = combined[combined["Age"].isnull()]

In [315]:
names

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
2541,Chauncey Billups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2009,33.0,1210.0,0.027
3021,Clyde Drexler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1995,3.0,1050.0,0.003
4387,Derrick Rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,10.0,1010.0,0.010
4637,Dominique Wilkins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1994,1.0,1010.0,0.001
5828,George Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1981,3.0,690.0,0.004
6010,Goran DragiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2014,3.0,1250.0,0.002
7096,James Harden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,1.0,1010.0,0.001
10463,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020,200.0,1010.0,0.198
10464,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,42.0,1010.0,0.042
10465,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,146.0,1000.0,0.146
10466,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2023,10.0,1000.0,0.010
10467,Luka DonÄiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2024,566.0,990.0,0.572
10674,Manu GinÃ³bili,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2008,9.0,1260.0,0.007
10675,Manu GinÃ³bili,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2010,3.0,1230.0,0.002
10676,Manu GinÃ³bili,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2011,20.0,1210.0,0.017
12299,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019,212.0,1010.0,0.210
12300,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020,18.0,1010.0,0.018
12301,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,971.0,1010.0,0.961
12302,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,875.0,1000.0,0.875
12303,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2023,674.0,1000.0,0.674
12304,Nikola JokiÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2024,926.0,990.0,0.935
12823,Peja StojakoviÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2002,1.0,1260.0,0.001
12824,Peja StojakoviÄ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2004,281.0,1230.0,0.228
14942,Stephen Jackson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2010,1.0,1230.0,0.001
16371,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2005,3.0,1270.0,0.002

In [321]:
mvps

                  Player  Pts Won  Pts Max  Share  Year
0          Julius Erving    454.0      690  0.658  1981
1             Larry Bird    423.0      690  0.613  1981
2    Kareem Abdul-Jabbar    286.0      690  0.414  1981
3           Moses Malone    180.0      690  0.261  1981
4          George Gervin     83.0      690  0.120  1981
..                   ...      ...      ...    ...   ...
705        Jalen Brunson    142.0      990  0.143  2024
706         Jayson Tatum     86.0      990  0.087  2024
707      Anthony Edwards     18.0      990  0.018  2024
708     Domantas Sabonis      3.0      990  0.003  2024
709         Kevin Durant      1.0      990  0.001  2024

[710 rows x 5 columns]

In [322]:
# Replace all instances of "apple" with "orange" in "Column1"
mvps["Player"] = mvps["Player"].replace("Luka DonÄiÄ", "Luka Dončić")

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\4030334513.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mvps["Player"] = mvps["Player"].replace("Luka DonÄiÄ", "Luka Dončić")

In [324]:
mvps.tail(10)

                      Player  Pts Won  Pts Max  Share  Year
700                Ja Morant      1.0     1000  0.001  2023
701            Nikola JokiÄ    926.0      990  0.935  2024
702  Shai Gilgeous-Alexander    640.0      990  0.646  2024
703              Luka Dončić    566.0      990  0.572  2024
704    Giannis Antetokounmpo    192.0      990  0.194  2024
705            Jalen Brunson    142.0      990  0.143  2024
706             Jayson Tatum     86.0      990  0.087  2024
707          Anthony Edwards     18.0      990  0.018  2024
708         Domantas Sabonis      3.0      990  0.003  2024
709             Kevin Durant      1.0      990  0.001  2024

In [325]:
mvps["Player"] = mvps["Player"].replace("Manu GinÃ³bili", "Manu Ginóbili")

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\2043908812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mvps["Player"] = mvps["Player"].replace("Manu GinÃ³bili", "Manu Ginóbili")

In [326]:
mvps["Player"] = mvps["Player"].replace("Nikola JokiÄ", "Nikola Jokić")

C:\Users\salya\AppData\Local\Temp\ipykernel_30488\2351947549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mvps["Player"] = mvps["Player"].replace("Nikola JokiÄ", "Nikola Jokić")